package:
  name: pyqode.python
  version: "2.6.3"

source:
  fn: pyqode.python-2.6.3.tar.gz
  url: https://pypi.python.org/packages/source/p/pyqode.python/pyqode.python-2.6.3.tar.gz
  md5: 766bcf54f453d49f2a064b8265bb2b27
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pyqode.python = pyqode.python:main
    #
    # Would create an entry point called pyqode.python that calls pyqode.python.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - pyqode.qt
    - pyqode.core
    - jedi
    - pep8
    - pyflakes
    - docutils

  run:
    - python
    - setuptools
    - pyqode.qt
    - pyqode.core
    - jedi
    - pep8
    - pyflakes
    - docutils

test:
  # Python imports
  imports:
    - pyqode
    - pyqode.python
    - pyqode.python._forms
    - pyqode.python.backend
    - pyqode.python.managers
    - pyqode.python.modes
    - pyqode.python.panels
    - pyqode.python.widgets

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/pyQode/pyqode.python
  license: MIT License
  summary: 'Adds python support to pyqode.core'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
