package:
  name: metis
  version: "5.1.0"

source:
  url: http://glaros.dtc.umn.edu/gkhome/fetch/sw/metis/metis-5.1.0.tar.gz
  fn: metis-5.1.0.tar.gz

build:
  number: 0

requirements:
  build:
    - cmake
  run:

test:
  commands:

about:
  home: http://glaros.dtc.umn.edu/gkhome/views/metis
  license: Apache License
  license_file: LICENSE.txt
