package:
  name: vtk
  version: 6.2.0

source:
  git_rev: "v6.2.0"
  git_url: https://gitlab.kitware.com/vtk/vtk.git

build:
  number: 0

requirements:
  build:
    - cmake
    - python
    - qt
  run:
    - python

test:
  commands:
    - vtkpython -h
  imports:
    - vtk

about:
  home: http://www.vtk.org/
  license: BSD
